// The Lua emitters build a file line by line; collecting into a vec literal
// would put the whole document in one expression.
#![allow(clippy::vec_init_then_push)]
//! Full `mapinfo.lua` emission.
//!
//! Values default to what a shipped Zero-K 1v1 actually declares, measured in
//! measured reference maps. The Map-Blueprint project's
//! defaults (`maxMetal = 0.02`, `extractorRadius = 500`) are **not**
//! conventions — `extractorRadius` drives merge validation, so a wrong default
//! produces misleading warnings.

use springen_core::lua::num;
use springen_core::project::Project;
use springen_core::spring::Derived;

/// SSMF resources shipped alongside the SMF, and the splat channel scaling.
#[derive(Clone, Debug)]
pub struct Resources {
    pub smt_files: Vec<String>,
    pub splat_distr_tex: Option<String>,
    pub specular_tex: Option<String>,
    pub metalmap_tex: Option<String>,
    pub typemap_tex: Option<String>,
    pub grassmap_tex: Option<String>,
    /// The single tile Spring multiplies over the whole diffuse.
    pub detail_tex: Option<String>,
    /// The legacy splat path: one RGBA tile whose channels line up with the
    /// distribution's, each used as a monochrome detail.
    pub splat_detail_tex: Option<String>,
    /// The modern path: four detail normal maps, one per distribution channel.
    /// With `splat_detail_normal_diffuse_alpha` set, alpha carries a diffuse
    /// modulation as well as the normal in RGB.
    pub splat_detail_normal_tex: [Option<String>; 4],
    pub splat_detail_normal_diffuse_alpha: bool,
    /// Per **RGBA** channel — there are four splat textures, not three.
    pub splat_tex_scales: [f64; 4],
    pub splat_tex_mults: [f64; 4],
}

impl Default for Resources {
    fn default() -> Self {
        Resources {
            smt_files: Vec::new(),
            splat_distr_tex: None,
            specular_tex: None,
            metalmap_tex: None,
            typemap_tex: None,
            grassmap_tex: None,
            detail_tex: None,
            splat_detail_tex: None,
            splat_detail_normal_tex: [None, None, None, None],
            splat_detail_normal_diffuse_alpha: true,
            // Measured from a shipped map, and shared with the material
            // blender so the baked texture and the GPU detail agree.
            splat_tex_scales: springen_core::material::DEFAULT_TEX_SCALES,
            splat_tex_mults: [0.6, 0.3, 0.3, 0.4],
        }
    }
}

fn quad(v: &[f64; 4]) -> String {
    v.iter().map(|f| num(*f)).collect::<Vec<_>>().join(", ")
}

fn triple(v: &[f64; 3]) -> String {
    format!(
        "{{{}}}",
        v.iter().map(|f| num(*f)).collect::<Vec<_>>().join(", ")
    )
}

/// `height_range` is the range the heightmap samples were actually baked
/// against, which under `HeightMode::Fit` is not the range the project
/// declares — see `springen_core::bake::height_and_range`. Writing the
/// project's numbers here instead moves every elmo height in the map.
pub fn mapinfo_lua(
    project: &Project,
    derived: &Derived,
    res: &Resources,
    height_range: (f64, f64),
) -> String {
    let short = project.short_name();
    let mut l: Vec<String> = Vec::new();
    l.push(format!(
        "-- Generated by Springen. Size {}x{} ({} x {} elmos, mapx={}).",
        derived.units_x, derived.units_y, derived.elmos_x, derived.elmos_y, derived.mapx
    ));
    l.push("-- Keys are lowercased by the map's own lowerkeys() helper, so case here".into());
    l.push("-- is cosmetic. Files in mapconfig/mapinfo/*.lua are merged over this table.".into());
    l.push(String::new());
    l.push("local mapinfo = {".into());
    l.push(format!("\tname        = \"{}\",", project.name));
    l.push(format!("\tshortname   = \"{short}\","));
    l.push(format!("\tdescription = \"{}\",", project.description));
    l.push(format!("\tauthor      = \"{}\",", project.author));
    l.push(format!("\tversion     = \"{}\",", project.version));
    l.push("\tmodtype     = 3,".into());
    l.push("\tdepend      = {\"Map Helper v1\"},".into());
    l.push(String::new());
    l.push(format!("\tmaphardness     = {},", num(project.hardness)));
    l.push("\tnotDeformable   = false,".into());
    l.push(format!("\tgravity         = {},", num(project.gravity)));
    l.push(format!("\ttidalStrength   = {},", num(project.tidal)));
    l.push(format!("\tmaxMetal        = {},", num(project.max_metal)));
    l.push(format!(
        "\textractorRadius = {},",
        num(project.extractor_radius)
    ));
    l.push("\tvoidWater       = false,".into());
    l.push("\tvoidGround      = false,".into());
    l.push("\tautoShowMetal   = true,".into());
    l.push(String::new());
    l.push("\tsmf = {".into());
    l.push(format!("\t\tminHeight = {},", num(height_range.0)));
    l.push(format!("\t\tmaxHeight = {},", num(height_range.1)));
    for (i, f) in res.smt_files.iter().enumerate() {
        l.push(format!("\t\tsmtFileName{i} = \"{f}\","));
    }
    // These four layers can ship as external images instead of SMF blocks,
    // which means they can be iterated without recompiling the map.
    for (key, val) in [
        ("minimapTex", None::<&String>),
        ("metalmapTex", res.metalmap_tex.as_ref()),
        ("typemapTex", res.typemap_tex.as_ref()),
        ("grassmapTex", res.grassmap_tex.as_ref()),
    ] {
        if let Some(v) = val {
            l.push(format!("\t\t{key} = \"{v}\","));
        }
    }
    l.push("\t},".into());
    l.push(String::new());
    l.push("\tresources = {".into());
    if let Some(v) = &res.detail_tex {
        l.push(format!("\t\tdetailTex     = \"{v}\","));
    }
    if let Some(v) = &res.splat_distr_tex {
        l.push(format!("\t\tsplatDistrTex = \"{v}\","));
    }
    if let Some(v) = &res.splat_detail_tex {
        l.push(format!("\t\tsplatDetailTex = \"{v}\","));
    }
    if let Some(v) = &res.specular_tex {
        l.push(format!("\t\tspecularTex   = \"{v}\","));
    }
    for (i, v) in res.splat_detail_normal_tex.iter().enumerate() {
        if let Some(v) = v {
            l.push(format!("\t\tsplatDetailNormalTex{} = \"{v}\",", i + 1));
        }
    }
    if res.splat_detail_normal_tex.iter().any(Option::is_some) {
        l.push(format!(
            "\t\tsplatDetailNormalDiffuseAlpha = {},",
            res.splat_detail_normal_diffuse_alpha
        ));
    }
    l.push("\t},".into());
    l.push(String::new());
    l.push("\t-- Per RGBA channel of the splat distribution texture.".into());
    l.push("\tsplats = {".into());
    l.push(format!(
        "\t\ttexScales = {{{}}},",
        quad(&res.splat_tex_scales)
    ));
    l.push(format!(
        "\t\ttexMults  = {{{}}},",
        quad(&res.splat_tex_mults)
    ));
    l.push("\t},".into());
    l.push(String::new());
    let env = &project.environment;
    let sun = env.sun_dir();
    l.push(format!("\t-- Environment preset: {}", env.preset));
    l.push("\tatmosphere = {".into());
    l.push(format!("\t\tminWind = {},", num(env.min_wind)));
    l.push(format!("\t\tmaxWind = {},", num(env.max_wind)));
    l.push(format!("\t\tfogStart = {},", num(env.fog_start)));
    l.push(format!("\t\tfogEnd   = {},", num(env.fog_end)));
    l.push(format!("\t\tfogColor = {},", triple(&env.fog_color)));
    l.push(format!("\t\tsunColor = {},", triple(&env.sun_color)));
    l.push(format!("\t\tskyColor = {},", triple(&env.sky_color)));
    l.push(format!("\t\tcloudColor = {},", triple(&env.cloud_color)));
    l.push(format!("\t\tcloudDensity = {},", num(env.cloud_density)));
    if let Some(sky) = &env.skybox {
        l.push(format!("\t\tskyBox = \"{sky}\","));
    }
    l.push("\t},".into());
    l.push(String::new());
    l.push(format!(
        "\t-- Sun at {}° bearing, {}° above the horizon.",
        num(env.sun_azimuth),
        num(env.sun_elevation)
    ));
    l.push("\tlighting = {".into());
    l.push(format!("\t\tsunDir = {},", triple(&sun)));
    l.push(format!(
        "\t\tgroundAmbientColor  = {},",
        triple(&env.ground_ambient)
    ));
    l.push(format!(
        "\t\tgroundDiffuseColor  = {},",
        triple(&env.ground_diffuse)
    ));
    l.push(format!(
        "\t\tgroundSpecularColor = {},",
        triple(&env.ground_specular)
    ));
    l.push(format!(
        "\t\tgroundShadowDensity = {},",
        num(env.shadow_density)
    ));
    l.push(format!(
        "\t\tunitAmbientColor    = {},",
        triple(&env.ground_ambient)
    ));
    l.push(format!(
        "\t\tunitDiffuseColor    = {},",
        triple(&env.ground_diffuse)
    ));
    l.push(format!(
        "\t\tunitSpecularColor   = {},",
        triple(&env.sun_color)
    ));
    l.push(format!(
        "\t\tunitShadowDensity   = {},",
        num(env.shadow_density)
    ));
    l.push("\t\tspecularExponent    = 100.0,".into());
    l.push("\t},".into());
    l.push(String::new());
    l.push("\twater = {".into());
    l.push("\t\tdamage = 0.0,".into());
    l.push("\t\trepeatX = 0.0,".into());
    l.push("\t\trepeatY = 0.0,".into());
    l.push(format!("\t\tabsorb  = {},", triple(&env.water_absorb)));
    l.push(format!("\t\tbaseColor = {},", triple(&env.water_base)));
    l.push(format!("\t\tminColor  = {},", triple(&env.water_min)));
    l.push(format!(
        "\t\tsurfaceColor = {},",
        triple(&env.water_surface)
    ));
    l.push("\t\tsurfaceAlpha = 0.03,".into());
    l.push("\t\thasWaterPlane = false,".into());
    l.push("\t\tforceRendering = false,".into());
    l.push("\t},".into());
    l.push(String::new());
    l.push("\t-- Zero-K ignores these and uses mapconfig/map_startboxes.lua.".into());
    l.push("\tteams = {".into());
    let cx = f64::from(derived.elmos_x) / 2.0;
    let cz = f64::from(derived.elmos_y) / 2.0;
    for t in 0..2 {
        l.push(format!(
            "\t\t[{t}] = {{startPos = {{x = {}, z = {}}}}},",
            num(cx),
            num(cz)
        ));
    }
    l.push("\t},".into());
    l.push(String::new());
    l.push("\tterrainTypes = {".into());
    l.push("\t\t[0] = {".into());
    l.push("\t\t\tname = \"Default\", hardness = 1.0, receiveTracks = true,".into());
    l.push("\t\t\tmoveSpeeds = {tank = 1.0, kbot = 1.0, hover = 1.0, ship = 1.0},".into());
    l.push("\t\t},".into());
    l.push("\t\t[1] = {".into());
    l.push("\t\t\tname = \"Rock\", hardness = 4.0, receiveTracks = false,".into());
    l.push("\t\t\tmoveSpeeds = {tank = 0.8, kbot = 0.9, hover = 1.0, ship = 1.0},".into());
    l.push("\t\t},".into());
    l.push("\t},".into());
    l.push("}".into());
    l.push(String::new());
    l.push("local function lowerkeys(t)".into());
    l.push("\tlocal out = {}".into());
    l.push("\tfor k, v in pairs(t) do".into());
    l.push("\t\tlocal nk = type(k) == \"string\" and k:lower() or k".into());
    l.push("\t\tout[nk] = type(v) == \"table\" and lowerkeys(v) or v".into());
    l.push("\tend".into());
    l.push("\treturn out".into());
    l.push("end".into());
    l.push(String::new());
    l.push("mapinfo = lowerkeys(mapinfo)".into());
    l.push(String::new());
    l.push("-- Merge every mapconfig/mapinfo/*.lua over the base table, sorted by".into());
    l.push("-- filename. This is how map options such as low/normal/high metal work.".into());
    l.push("if VFS then".into());
    l.push("\tlocal files = VFS.DirList(\"mapconfig/mapinfo/\", \"*.lua\")".into());
    l.push("\ttable.sort(files)".into());
    l.push("\tfor _, f in ipairs(files) do".into());
    l.push("\t\tlocal chunk = VFS.Include(f)".into());
    l.push("\t\tif type(chunk) == \"table\" then".into());
    l.push("\t\t\tfor k, v in pairs(lowerkeys(chunk)) do mapinfo[k] = v end".into());
    l.push("\t\tend".into());
    l.push("\tend".into());
    l.push("end".into());
    l.push(String::new());
    l.push("return mapinfo".into());
    l.join("\n")
}

pub fn mapoptions_lua() -> String {
    let mut l: Vec<String> = Vec::new();
    l.push("-- mapoptions.lua".into());
    l.push("-- Generated by Springen. Selected options land in mapconfig/mapinfo/.".into());
    l.push("return {".into());
    l.push("\t{".into());
    l.push("\t\tkey  = \"metalmult\",".into());
    l.push("\t\tname = \"Metal multiplier\",".into());
    l.push("\t\tdesc = \"Scales every metal spot's value at load.\",".into());
    l.push("\t\ttype = \"number\",".into());
    l.push("\t\tdef  = 1.0,".into());
    l.push("\t\tmin  = 0.1,".into());
    l.push("\t\tmax  = 10.0,".into());
    l.push("\t\tstep = 0.1,".into());
    l.push("\t},".into());
    l.push("}".into());
    l.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use springen_core::spring::derive;

    #[test]
    fn declares_the_smt_it_ships_and_the_full_rgba_splat_set() {
        let p = Project {
            name: "Test Map".into(),
            ..Default::default()
        };
        let d = derive(12, 12);
        let res = Resources {
            smt_files: vec!["testmap.smt".into()],
            splat_distr_tex: Some("testmap_splat.png".into()),
            specular_tex: Some("testmap_spec.png".into()),
            ..Default::default()
        };
        let lua = mapinfo_lua(&p, &d, &res, (p.min_height, p.max_height));
        assert!(lua.contains("smtFileName0 = \"testmap.smt\""));
        assert!(lua.contains("splatDistrTex = \"testmap_splat.png\""));
        // Four values per splat key, not three.
        assert!(lua.contains("texScales = {0.006, 0.003, 0.0058, 0.006}"));
        assert!(lua.contains("texMults  = {0.6, 0.3, 0.3, 0.4}"));
        assert!(lua.contains("depend      = {\"Map Helper v1\"}"));
        assert!(lua.contains("modtype     = 3"));
        assert!(lua.ends_with("return mapinfo"));
        // The measured defaults, not the blueprint's.
        assert!(lua.contains("maxMetal        = 1.7"));
        assert!(lua.contains("extractorRadius = 100"));
    }

    #[test]
    fn short_name_strips_punctuation() {
        let p = Project {
            name: "Ridge & Valley 12!".into(),
            ..Default::default()
        };
        assert_eq!(p.short_name(), "RidgeValley12");
    }
}
