#![allow(clippy::vec_init_then_push)]
//! Lua emission: `mapinfo.lua`, `mapconfig/map_metal_layout.lua`,
//! `mapconfig/map_startboxes.lua`, and the mapconv bridge script.

use crate::field::SharedField;
use crate::project::{water_level_t, Context, Project};
use crate::spring::Derived;
use crate::zk::{symmetry_images, BuildMask, BuildabilityOptions, MetalSpot, Zk};

/// Format a number the way the prototype's string coercion did: integers
/// without a decimal point, everything else shortest round-trip.
pub fn num(v: f64) -> String {
    format!("{v}")
}

/// `toFixed(2)` with a trailing `.00` stripped, which is how metal values are
/// written into the layout table.
fn metal_num(v: f64) -> String {
    let s = format!("{:.2}", v);
    s.strip_suffix(".00").map(str::to_string).unwrap_or(s)
}

/// The compact `mapinfo.lua` the prototype emitted. Archive builds use
/// `springen_archive::mapinfo` instead, which writes the full key set.
pub fn mapinfo_lua(project: &Project, derived: &Derived) -> String {
    let name = if project.name.is_empty() {
        "Untitled"
    } else {
        &project.name
    };
    let short = project.short_name();
    let mut l: Vec<String> = Vec::new();
    l.push(format!(
        "-- Generated by MapForge. Size {}x{} ({}x{} elmos, mapx={})",
        derived.units_x, derived.units_y, derived.elmos_x, derived.elmos_y, derived.mapx
    ));
    l.push("local mapinfo = {".into());
    l.push(format!("  name        = \"{name}\","));
    l.push(format!("  shortname   = \"{short}\","));
    l.push(format!("  description = \"{}\",", project.description));
    l.push(format!("  author      = \"{}\",", project.author));
    l.push("  version     = \"1.0\",".into());
    l.push(format!(
        "  mapfile     = \"maps/{}.smf\",",
        short.to_lowercase()
    ));
    l.push("  modtype     = 3,".into());
    l.push(format!("  maphardness = {},", num(project.hardness)));
    l.push(format!("  gravity     = {},", num(project.gravity)));
    l.push(format!("  tidalStrength = {},", num(project.tidal)));
    l.push(format!("  maxMetal    = {},", num(project.max_metal)));
    l.push(format!(
        "  extractorRadius = {},",
        num(project.extractor_radius)
    ));
    l.push("  voidWater   = false,".into());
    l.push("  autoShowMetal = true,".into());
    l.push("  smf = {".into());
    l.push(format!("    minHeight = {},", num(project.min_height)));
    l.push(format!("    maxHeight = {},", num(project.max_height)));
    l.push("  },".into());
    l.push("  terrainTypes = {".into());
    l.push("    [0] = { name = 'Default', hardness = 1.0, receiveTracks = true,".into());
    l.push(
        "            moveSpeeds = { tank = 1.0, kbot = 1.0, hover = 1.0, ship = 1.0 } },".into(),
    );
    l.push("    [1] = { name = 'Rock',    hardness = 4.0, receiveTracks = false,".into());
    l.push(
        "            moveSpeeds = { tank = 0.8, kbot = 0.9, hover = 1.0, ship = 1.0 } },".into(),
    );
    l.push("  },".into());
    l.push("}".into());
    l.push("return mapinfo".into());
    l.join("\n")
}

#[derive(Clone, Debug, Default)]
pub struct MetalLayoutOptions {
    pub symmetry: Option<String>,
    pub need_mex_drawing: bool,
    /// Emit the player-count-dependent spot sets Zero-K layouts use.
    pub player_count_sets: bool,
}

/// Emit `mapconfig/map_metal_layout.lua`.
///
/// Explicit metal values are **always** written. Omit them and Zero-K
/// integrates the metalmap raster instead, which makes the economy depend on
/// how blobs happened to be painted and change whenever the raster changes.
pub fn metal_layout_lua(spots: &[MetalSpot], opts: &MetalLayoutOptions) -> String {
    let live: Vec<&MetalSpot> = spots.iter().filter(|s| s.live()).collect();
    let mut l: Vec<String> = Vec::new();
    l.push("-- mapconfig/map_metal_layout.lua".into());
    l.push(format!(
        "-- Generated by MapForge. {} spots, coordinates in elmos,",
        live.len()
    ));
    l.push(format!(
        "-- snapped to the {}-elmo metal grid (Game.metalMapSquareSize).",
        num(Zk::METAL_GRID)
    ));
    l.push("-- Explicit metal values are written so Zero-K does not integrate the".into());
    l.push(format!(
        "-- metalmap raster (mex_spot_finder.lua: DEFAULT_MEX_INCOME = {}, values <= {} are dropped).",
        num(Zk::DEFAULT_MEX_INCOME),
        num(Zk::MINIMUM_MEX_INCOME)
    ));
    if let Some(sym) = &opts.symmetry {
        if sym != "none" {
            l.push(format!("-- Symmetry: {sym}"));
        }
    }
    l.push(String::new());
    l.push("return {".into());
    l.push("\tspots = {".into());
    for s in &live {
        l.push(format!(
            "\t\t{{ x = {}, z = {}, metal = {} }},",
            num(s.x.round()),
            num(s.z.round()),
            metal_num(s.metal)
        ));
    }
    l.push("\t},".into());
    if opts.need_mex_drawing {
        l.push("\tneedMexDrawing = true,".into());
    }
    l.push("}".into());
    l.join("\n")
}

/// Emit the player-count spot-set scaffold real Zero-K layouts use.
///
/// The gameplay judgement of which spots belong to a duel versus a team game
/// cannot be generated, so every spot goes in `allspots` and the other sets are
/// left for the author to fill in.
pub fn metal_layout_lua_with_sets(spots: &[MetalSpot], opts: &MetalLayoutOptions) -> String {
    let live: Vec<&MetalSpot> = spots.iter().filter(|s| s.live()).collect();
    let mut l: Vec<String> = Vec::new();
    l.push("-- mapconfig/map_metal_layout.lua".into());
    l.push("-- Generated by Springen.".into());
    l.push("-- Spot sets are selected by live player count, counting AIs and".into());
    l.push("-- non-spectator humans at load. Springen cannot make that gameplay".into());
    l.push("-- judgement, so every generated spot is in allspots; fill the others in.".into());
    l.push(String::new());
    l.push("local allspots = {".into());
    for s in &live {
        l.push(format!(
            "\t{{ x = {}, z = {}, metal = {} }},",
            num(s.x.round()),
            num(s.z.round()),
            metal_num(s.metal)
        ));
    }
    l.push("}".into());
    l.push(String::new());
    l.push("local duelspots  = {}".into());
    l.push("local twospots   = {}".into());
    l.push("local threespots = {}".into());
    l.push("local teamspots  = {}".into());
    l.push(String::new());
    l.push("local function playerCount()".into());
    l.push("\tlocal n = 0".into());
    l.push("\tfor _, teamID in ipairs(Spring.GetTeamList() or {}) do".into());
    l.push("\t\tif teamID ~= Spring.GetGaiaTeamID() then n = n + 1 end".into());
    l.push("\tend".into());
    l.push("\treturn n".into());
    l.push("end".into());
    l.push(String::new());
    l.push("local spots = {}".into());
    l.push("for _, s in ipairs(allspots) do spots[#spots + 1] = s end".into());
    l.push("local pcount = playerCount()".into());
    l.push("local extra = (pcount <= 2 and duelspots)".into());
    l.push("\tor (pcount <= 4 and twospots)".into());
    l.push("\tor (pcount <= 6 and threespots)".into());
    l.push("\tor teamspots".into());
    l.push("for _, s in ipairs(extra) do spots[#spots + 1] = s end".into());
    l.push(String::new());
    l.push("return {".into());
    l.push("\tspots = spots,".into());
    if opts.need_mex_drawing {
        l.push("\tneedMexDrawing = true,".into());
    }
    l.push("}".into());
    l.join("\n")
}

/// One team's start area.
#[derive(Clone, Debug)]
pub struct StartBox {
    pub name_long: String,
    pub name_short: String,
    /// Corners read clockwise around the polygon, in elmos.
    pub boxes: Vec<Vec<(f64, f64)>>,
    pub start_points: Vec<(f64, f64)>,
    /// Whether the start point was placed on ground that was checked, rather
    /// than fallen back to the box's geometric centre.
    pub grounded: bool,
}

/// Emit `mapconfig/map_startboxes.lua`. Zero-K ignores `mapinfo.teams[].startPos`
/// and uses this instead.
pub fn startboxes_lua(teams: &[StartBox]) -> String {
    let mut l: Vec<String> = Vec::new();
    l.push("-- mapconfig/map_startboxes.lua".into());
    l.push("-- Generated by Springen. Coordinates in elmos, corners clockwise.".into());
    l.push("return {".into());
    for (i, t) in teams.iter().enumerate() {
        l.push(format!("\t[{i}] = {{"));
        l.push("\t\tstartpoints = {".into());
        for (x, z) in &t.start_points {
            l.push(format!("\t\t\t{{ {}, {} }},", num(*x), num(*z)));
        }
        l.push("\t\t},".into());
        l.push("\t\tboxes = {".into());
        for b in &t.boxes {
            let corners: Vec<String> = b
                .iter()
                .map(|(x, z)| format!("{{{}, {}}}", num(*x), num(*z)))
                .collect();
            l.push(format!("\t\t\t{{ {} }},", corners.join(", ")));
        }
        l.push("\t\t},".into());
        l.push(format!("\t\tnameLong = \"{}\",", t.name_long));
        l.push(format!("\t\tnameShort = \"{}\",", t.name_short));
        l.push("\t},".into());
    }
    l.push("}".into());
    l.join("\n")
}

/// One feature for the FeaturePlacer gadget.
#[derive(Clone, Debug)]
pub struct PlacedFeature {
    pub name: String,
    pub x: f64,
    pub z: f64,
    /// Heading, as FeaturePlacer writes it: a string, in degrees.
    pub rot: i32,
}

impl PlacedFeature {
    /// A geothermal vent. In Zero-K a geo is just a feature named `geovent`.
    pub fn geovent(x: f64, z: f64) -> PlacedFeature {
        PlacedFeature {
            name: "geovent".into(),
            x,
            z,
            rot: 0,
        }
    }
}

/// Emit `mapconfig/featureplacer/set.lua`.
///
/// The older of the engine's two feature paths and by far the simpler: three
/// flat lists of name and position. It is chosen over s11n deliberately — s11n
/// carries full per-feature state and is what the reference map uses, but
/// nothing here needs per-feature health or collision volumes, and the SMF
/// feature block is still blocked on open question C1.
pub fn featureplacer_lua(features: &[PlacedFeature]) -> String {
    let mut l: Vec<String> = Vec::new();
    l.push("-- mapconfig/featureplacer/set.lua".into());
    l.push("-- Generated by Springen. Coordinates in elmos.".into());
    l.push("-- A geothermal vent is a feature named 'geovent'; the engine reads".into());
    l.push("-- these lists rather than the SMF feature block.".into());
    l.push(String::new());
    l.push("local unitlist = {}".into());
    l.push("local buildinglist = {}".into());
    l.push("local objectlist = {".into());
    for f in features {
        l.push(format!(
            "\t{{ name = '{}', x = {}, z = {}, rot = \"{}\" }},",
            f.name,
            num(f.x.round()),
            num(f.z.round()),
            f.rot
        ));
    }
    l.push("}".into());
    l.push(String::new());
    l.push("return {".into());
    l.push("\tunitlist = unitlist,".into());
    l.push("\tbuildinglist = buildinglist,".into());
    l.push("\tobjectlist = objectlist,".into());
    l.push("}".into());
    l.join("\n")
}

/// Short name, long name and the polygon, before a start point is chosen.
type TeamBox = (&'static str, &'static str, Vec<(f64, f64)>);
/// As [`TeamBox`], but named at runtime — an edited box carries whatever name
/// the project gave it.
type NamedBox = (String, String, Vec<(f64, f64)>);

/// The terrain a start position has to stand on.
pub struct StartGround<'a> {
    pub height: &'a SharedField,
    pub ctx: &'a Context,
    pub build: BuildabilityOptions,
    /// Half-extent of clear ground a start position wants around it, in elmos,
    /// tried largest first. A commander lands with a factory to place.
    pub room: Vec<f64>,
}

impl<'a> StartGround<'a> {
    pub fn new(height: &'a SharedField, ctx: &'a Context, build: BuildabilityOptions) -> Self {
        StartGround {
            height,
            ctx,
            build,
            room: vec![384.0, 256.0, 192.0, 128.0, 64.0],
        }
    }
}

/// Start boxes derived from the map size, one per team the symmetry implies.
///
/// Geometry only: start points land on the box centroid, wherever that is.
/// Use [`startboxes_on`] when the terrain is available.
pub fn default_startboxes(derived: &Derived, symmetry: &str) -> Vec<StartBox> {
    startboxes_on(derived, symmetry, None)
}

/// One box per team, with each start point on the largest patch of buildable
/// flat inside it.
///
/// Two things were wrong with deriving the point from the box alone. It is the
/// centroid of a rectangle, so on a map that is 96.9% submerged the commander
/// spawns on the sea floor; and the box count branched on `mirrorY` and
/// `diagonal` only, so a `rot90` or `quad` map — four-way symmetric, four
/// teams — got two boxes covering half the map each.
pub fn startboxes_on(
    derived: &Derived,
    symmetry: &str,
    ground: Option<&StartGround>,
) -> Vec<StartBox> {
    startboxes_from(&default_areas(derived, symmetry), derived, symmetry, ground)
}

/// An editable start box: a named polygon in elmos.
///
/// Split from [`StartBox`] because they answer different questions. A
/// `StartArea` is what a person draws and a project stores; a `StartBox` is
/// that plus the start point chosen inside it, which depends on the terrain
/// and so cannot be known until the graph has been evaluated. Storing the
/// second would freeze a commander onto ground that a later edit moved.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StartArea {
    pub short: String,
    pub long: String,
    /// Corners clockwise, in elmos.
    pub poly: Vec<(f64, f64)>,
}

impl StartArea {
    /// The axis-aligned bounds, which is what a drag handle moves.
    pub fn bounds(&self) -> (f64, f64, f64, f64) {
        let mut b = (f64::MAX, f64::MAX, f64::MIN, f64::MIN);
        for (x, z) in &self.poly {
            b.0 = b.0.min(*x);
            b.1 = b.1.min(*z);
            b.2 = b.2.max(*x);
            b.3 = b.3.max(*z);
        }
        b
    }
    pub fn centre(&self) -> (f64, f64) {
        let (x0, z0, x1, z1) = self.bounds();
        ((x0 + x1) * 0.5, (z0 + z1) * 0.5)
    }
    /// Move every corner, keeping the shape. Triangular `diagonal` boxes move
    /// like any other.
    pub fn translate(&mut self, dx: f64, dz: f64, w: f64, h: f64) {
        let (x0, z0, x1, z1) = self.bounds();
        // Clamped as a whole rather than per corner, or dragging into a wall
        // would squash the box against it.
        let dx = dx.clamp(-x0, w - x1);
        let dz = dz.clamp(-z0, h - z1);
        for p in self.poly.iter_mut() {
            p.0 += dx;
            p.1 += dz;
        }
    }
    /// Replace the polygon with an axis-aligned rectangle.
    ///
    /// The corners are ordered clockwise, which is what
    /// `mapconfig/map_startboxes.lua` documents and what the even-odd test in
    /// `inside` assumes.
    pub fn set_bounds(&mut self, x0: f64, z0: f64, x1: f64, z1: f64, w: f64, h: f64) {
        let (a, b) = (x0.min(x1).clamp(0.0, w), x0.max(x1).clamp(0.0, w));
        let (c, d) = (z0.min(z1).clamp(0.0, h), z0.max(z1).clamp(0.0, h));
        // A box with no area cannot hold a start point, so it keeps a floor.
        const MIN: f64 = 64.0;
        let b = if b - a < MIN { (a + MIN).min(w) } else { b };
        let d = if d - c < MIN { (c + MIN).min(h) } else { d };
        self.poly = vec![(a, c), (b, c), (b, d), (a, d)];
    }

    /// The shape this area currently is.
    pub fn shape(&self) -> Shape {
        match self.poly.len() {
            3 => Shape::Wedge,
            _ if self.is_rect() => Shape::Rect,
            _ => Shape::Free,
        }
    }

    fn is_rect(&self) -> bool {
        if self.poly.len() != 4 {
            return false;
        }
        let (x0, z0, x1, z1) = self.bounds();
        self.poly
            .iter()
            .all(|(x, z)| (*x == x0 || *x == x1) && (*z == z0 || *z == z1))
    }

    /// Re-cut the area to a shape, keeping the ground it covers.
    ///
    /// A wedge is the triangle against whichever corner of the bounds is
    /// nearest the map edge — which is where a corner start sits, and the
    /// shape `diagonal` symmetry has always produced.
    pub fn set_shape(&mut self, shape: Shape, w: f64, h: f64) {
        let (x0, z0, x1, z1) = self.bounds();
        match shape {
            Shape::Rect | Shape::Free => self.set_bounds(x0, z0, x1, z1, w, h),
            Shape::Wedge => {
                let (cx, cz) = ((x0 + x1) * 0.5, (z0 + z1) * 0.5);
                let west = cx < w * 0.5;
                let north = cz < h * 0.5;
                self.poly = match (west, north) {
                    (true, true) => vec![(x0, z0), (x1, z0), (x0, z1)],
                    (false, true) => vec![(x1, z0), (x1, z1), (x0, z0)],
                    (false, false) => vec![(x1, z1), (x0, z1), (x1, z0)],
                    (true, false) => vec![(x0, z1), (x0, z0), (x1, z1)],
                };
            }
        }
    }

    /// Scale about the centre, keeping the shape and staying on the map.
    pub fn scale(&mut self, k: f64, w: f64, h: f64) {
        let (cx, cz) = self.centre();
        for p in self.poly.iter_mut() {
            p.0 = (cx + (p.0 - cx) * k).clamp(0.0, w);
            p.1 = (cz + (p.1 - cz) * k).clamp(0.0, h);
        }
    }
}

/// What shape a start area is cut to.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Shape {
    Rect,
    /// A right triangle in a corner, which is what a corner start wants and
    /// what `diagonal` symmetry has always produced.
    Wedge,
    /// Anything else — an imported map's box, or one built by hand.
    Free,
}

impl Shape {
    pub const ALL: [Shape; 2] = [Shape::Rect, Shape::Wedge];
    pub fn label(self) -> &'static str {
        match self {
            Shape::Rect => "Rect",
            Shape::Wedge => "Wedge",
            Shape::Free => "Free",
        }
    }
}

/// The boxes a symmetry implies, before anyone has edited them.
pub fn default_areas(derived: &Derived, symmetry: &str) -> Vec<StartArea> {
    default_team_boxes(derived, symmetry)
        .into_iter()
        .map(|(short, long, poly)| StartArea {
            short: short.into(),
            long: long.into(),
            poly,
        })
        .collect()
}

/// Place a start point inside each of `areas`, from the terrain if there is
/// any.
pub fn startboxes_from(
    areas: &[StartArea],
    derived: &Derived,
    symmetry: &str,
    ground: Option<&StartGround>,
) -> Vec<StartBox> {
    let teams: Vec<NamedBox> = areas
        .iter()
        .map(|a| (a.short.clone(), a.long.clone(), a.poly.clone()))
        .collect();
    place_starts(teams, derived, symmetry, ground)
}

fn default_team_boxes(derived: &Derived, symmetry: &str) -> Vec<TeamBox> {
    let w = f64::from(derived.elmos_x);
    let h = f64::from(derived.elmos_y);
    let mx = w * 0.28;
    let my = h * 0.28;
    // Team count is the order of the symmetry group: a four-way symmetric map
    // has four fair starts, and pretending it has two hands each pair half
    // the map.
    let teams: Vec<TeamBox> = match symmetry {
        "quad" | "rot90" => vec![
            (
                "NW",
                "North-West",
                vec![(0.0, 0.0), (mx, 0.0), (mx, my), (0.0, my)],
            ),
            (
                "NE",
                "North-East",
                vec![(w - mx, 0.0), (w, 0.0), (w, my), (w - mx, my)],
            ),
            (
                "SE",
                "South-East",
                vec![(w - mx, h - my), (w, h - my), (w, h), (w - mx, h)],
            ),
            (
                "SW",
                "South-West",
                vec![(0.0, h - my), (mx, h - my), (mx, h), (0.0, h)],
            ),
        ],
        "mirrorY" => vec![
            ("N", "North", vec![(0.0, 0.0), (w, 0.0), (w, my), (0.0, my)]),
            (
                "S",
                "South",
                vec![(0.0, h - my), (w, h - my), (w, h), (0.0, h)],
            ),
        ],
        // Five-fold FFA: one box per team, each a square centred on its fifth
        // of a turn about the map centre. Wedges reaching the middle would be
        // fairer on paper and unusable in practice -- five boxes meeting at a
        // point put every commander's back against four neighbours at once.
        "rot72" => {
            let (cx, cz) = (w / 2.0, h / 2.0);
            // Far enough out that the boxes do not touch, near enough that a
            // corner of the map is not a base.
            let ring = w.min(h) * 0.31;
            let half = w.min(h) * 0.14;
            let names = [
                ("E", "East"),
                ("SE", "South-East"),
                ("SW", "South-West"),
                ("NW", "North-West"),
                ("NE", "North-East"),
            ];
            (0..5)
                .map(|k| {
                    // Due east, because that is where the `symmetry` node's
                    // fundamental wedge sits — it folds about the +x axis. A
                    // box ring starting anywhere else lands between the map's
                    // own five features rather than on them, and 90° is not a
                    // multiple of 72°, so "start at north" would put every
                    // base in the wrong place on the one map shape that needs
                    // them right.
                    let (bx, bz) = crate::zk::rotate_about_centre(cx + ring, cz, w, h, k);
                    let (x0, z0) = ((bx - half).max(0.0), (bz - half).max(0.0));
                    let (x1, z1) = ((bx + half).min(w), (bz + half).min(h));
                    (
                        names[k].0,
                        names[k].1,
                        vec![(x0, z0), (x1, z0), (x1, z1), (x0, z1)],
                    )
                })
                .collect()
        }
        "diagonal" => vec![
            ("NW", "North-West", vec![(0.0, 0.0), (mx, 0.0), (0.0, my)]),
            ("SE", "South-East", vec![(w, h), (w - mx, h), (w, h - my)]),
        ],
        _ => vec![
            ("W", "West", vec![(0.0, 0.0), (mx, 0.0), (mx, h), (0.0, h)]),
            (
                "E",
                "East",
                vec![(w - mx, 0.0), (w, 0.0), (w, h), (w - mx, h)],
            ),
        ],
    };

    teams
}

/// Choose the start point inside each box.
fn place_starts(
    mut teams: Vec<NamedBox>,
    derived: &Derived,
    symmetry: &str,
    ground: Option<&StartGround>,
) -> Vec<StartBox> {
    if teams.is_empty() {
        return Vec::new();
    }
    let w = f64::from(derived.elmos_x);
    let h = f64::from(derived.elmos_y);
    let mask = ground.map(|g| BuildMask::new(g.height, g.ctx, &g.build));
    let rooms: &[f64] = ground.map(|g| g.room.as_slice()).unwrap_or(&[]);

    // The first team's point is chosen from the terrain; the rest are its
    // images, so every team gets the same ground. An image that is not
    // buildable — generated terrain is only as symmetric as the graph that
    // made it — is re-chosen inside its own box instead.
    let mut out: Vec<StartBox> = Vec::with_capacity(teams.len());
    let primary = pick_start(&teams[0].2, mask.as_ref(), rooms, w, h);
    for (i, (short, long, poly)) in teams.drain(..).enumerate() {
        let (point, grounded) = if i == 0 {
            primary
        } else {
            // Whichever image of the primary lands in this box. Picking by
            // position rather than by index keeps quad and rot90 right, where
            // the operator's image order is not the boxes' order.
            let img = symmetry_images(primary.0 .0, primary.0 .1, symmetry, w, h)
                .into_iter()
                .find(|p| inside(&poly, *p));
            match (img, &mask) {
                (Some(p), Some(m)) if m.clear_within(p.0, p.1, rooms_min(rooms)) => (p, true),
                (Some(p), None) => (p, false),
                _ => pick_start(&poly, mask.as_ref(), rooms, w, h),
            }
        };
        out.push(StartBox {
            name_long: long,
            name_short: short,
            start_points: vec![(point.0.round(), point.1.round())],
            boxes: vec![poly],
            grounded,
        });
    }
    out
}

fn rooms_min(rooms: &[f64]) -> f64 {
    rooms.last().copied().unwrap_or(0.0)
}

/// Even-odd point-in-polygon, so triangular diagonal boxes work too.
fn inside(poly: &[(f64, f64)], p: (f64, f64)) -> bool {
    let mut hit = false;
    let n = poly.len();
    for i in 0..n {
        let (xi, zi) = poly[i];
        let (xj, zj) = poly[(i + n - 1) % n];
        if ((zi > p.1) != (zj > p.1)) && (p.0 < (xj - xi) * (p.1 - zi) / (zj - zi) + xi) {
            hit = !hit;
        }
    }
    hit
}

/// The best start position inside a box: the most open buildable ground,
/// tie-broken towards the box's centre so a team is not pushed into a corner.
fn pick_start(
    poly: &[(f64, f64)],
    mask: Option<&BuildMask>,
    rooms: &[f64],
    w: f64,
    h: f64,
) -> ((f64, f64), bool) {
    let n = poly.len() as f64;
    let centre = (
        poly.iter().map(|p| p.0).sum::<f64>() / n,
        poly.iter().map(|p| p.1).sum::<f64>() / n,
    );
    let Some(mask) = mask else {
        return (centre, false);
    };
    let x0 = poly.iter().map(|p| p.0).fold(f64::MAX, f64::min);
    let x1 = poly.iter().map(|p| p.0).fold(f64::MIN, f64::max);
    let z0 = poly.iter().map(|p| p.1).fold(f64::MAX, f64::min);
    let z1 = poly.iter().map(|p| p.1).fold(f64::MIN, f64::max);
    // Walk the box on the metal grid, which is fine enough that the answer is
    // the same as walking every lattice sample and coarse enough to be free.
    let step = Zk::METAL_GRID * 4.0;
    let mut best: Option<(usize, f64, (f64, f64))> = None;
    let mut z = z0;
    while z <= z1 {
        let mut x = x0;
        while x <= x1 {
            let p = (x.clamp(0.0, w), z.clamp(0.0, h));
            if inside(poly, p) {
                // Largest room this point has, as an index into `rooms`.
                if let Some(rank) = rooms.iter().position(|r| mask.clear_within(p.0, p.1, *r)) {
                    let d = (p.0 - centre.0).powi(2) + (p.1 - centre.1).powi(2);
                    let better = match &best {
                        None => true,
                        Some((br, bd, _)) => rank < *br || (rank == *br && d < *bd),
                    };
                    if better {
                        best = Some((rank, d, p));
                    }
                }
            }
            x += step;
        }
        z += step;
    }
    match best {
        Some((_, _, p)) => (p, true),
        // Nothing in the box is buildable. The centroid is no worse than any
        // other lie, and `grounded` says the point was not checked out.
        None => (centre, false),
    }
}

#[derive(Clone, Debug, Default)]
pub struct MapconvFiles {
    pub texture: Option<String>,
    pub height: Option<String>,
    pub metal: Option<String>,
    pub type_map: Option<String>,
    pub feature: Option<String>,
}

pub struct MapconvScript {
    pub command: String,
    pub script: String,
}

/// A ready-to-run mapconv invocation, kept because it is the escape hatch when
/// the native writer is not wanted.
pub fn mapconv_command(
    project: &Project,
    derived: &Derived,
    files: &MapconvFiles,
    compression: f64,
    shell_sh: bool,
) -> MapconvScript {
    let name: String = project
        .name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '-')
        .collect();
    let exe = if shell_sh { "./mapconv" } else { "MapConv.exe" };
    let mut parts = vec![
        exe.to_string(),
        "-i".into(),
        "-l".into(),
        format!("-c {}", num(compression)),
        format!("-x {}", num(project.max_height)),
        format!("-n {}", num(project.min_height)),
        format!("-o {name}.smf"),
    ];
    if let Some(f) = &files.texture {
        parts.push(format!("-t {f}"));
    }
    if let Some(f) = &files.height {
        parts.push(format!("-a {f}"));
    }
    if let Some(f) = &files.metal {
        parts.push(format!("-m {f}"));
    }
    if let Some(f) = &files.type_map {
        parts.push(format!("-y {f}"));
    }
    if let Some(f) = &files.feature {
        parts.push(format!("-f {f}"));
    }
    let command = parts.join(" ");
    let hash = if shell_sh { "#" } else { "REM" };
    let mut l: Vec<String> = Vec::new();
    if shell_sh {
        l.push("#!/bin/sh".into());
    }
    l.push(format!("{hash} Generated by Springen for {name}"));
    l.push(format!(
        "{hash} Map size {}x{} ({} elmos, mapx={})",
        derived.units_x, derived.units_y, derived.elmos_x, derived.mapx
    ));
    l.push(format!("{hash} Expected input sizes:"));
    l.push(format!(
        "{hash}   texture   {} x {}",
        derived.tex_w, derived.tex_h
    ));
    l.push(format!(
        "{hash}   heightmap {} x {}  (mapx+1)",
        derived.height_w, derived.height_h
    ));
    l.push(format!(
        "{hash}   metalmap  {} x {}  (texture/16)",
        derived.metal_w, derived.metal_h
    ));
    l.push(format!(
        "{hash}   typemap   {} x {}",
        derived.type_w, derived.type_h
    ));
    l.push(format!(
        "{hash} Waterline sits at height 0, i.e. {:.1}% up the range.",
        100.0 * water_level_t(project.min_height, project.max_height)
    ));
    l.push(String::new());
    l.push(command.clone());
    l.push(String::new());
    l.push(format!(
        "{hash} Then: copy {name}.smf and {name}.smt into mapcontainer.sdd/maps/"
    ));
    l.push(format!(
        "{hash} Archive as .sd7 with 7-Zip: ultra, dict 32M, word 64, NOT solid."
    ));
    MapconvScript {
        command,
        script: l.join("\n"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numbers_read_like_the_prototype_wrote_them() {
        assert_eq!(num(100.0), "100");
        assert_eq!(num(-80.0), "-80");
        assert_eq!(num(1.7), "1.7");
        assert_eq!(metal_num(2.0), "2");
        assert_eq!(metal_num(1.5), "1.50");
    }

    #[test]
    fn team_count_follows_the_symmetry_group() {
        let d = crate::spring::derive(12, 12);
        for two in ["none", "mirrorX", "mirrorY", "rot180", "diagonal"] {
            assert_eq!(default_startboxes(&d, two).len(), 2, "{two}");
        }
        // Four-way symmetric maps have four fair starts, not two.
        for four in ["quad", "rot90"] {
            assert_eq!(default_startboxes(&d, four).len(), 4, "{four}");
        }
        let names: Vec<String> = default_startboxes(&d, "quad")
            .iter()
            .map(|b| b.name_short.clone())
            .collect();
        assert_eq!(names, ["NW", "NE", "SE", "SW"]);
    }

    #[test]
    fn start_points_stand_on_dry_flat_ground() {
        use crate::field::{Field, SharedField};
        use crate::project::{Context, Project};
        use crate::zk::BuildabilityOptions;
        use std::sync::Arc;

        const R: usize = 129;
        let project = Project::default();
        let ctx = Context::new(&project, R);
        let d = crate::spring::derive(project.units_x, project.units_y);
        // Ocean, with one dry plateau in each half and nothing else.
        let mut f = Field::gray(R);
        for y in 0..R {
            for x in 0..R {
                // Chosen so each box has dry ground, but not at its centroid.
                let dry = (24..36).contains(&x) || (90..108).contains(&x);
                f.set(y * R + x, if dry { 0.6 } else { 0.0 });
            }
        }
        let height: SharedField = Arc::new(f);
        let sea = 0.3;

        let blind = default_startboxes(&d, "mirrorX");
        let sample = |p: (f64, f64)| {
            let s = (R - 1) as f64 / f64::from(d.elmos_x);
            height.at(
                (p.0 * s).round() as usize % R,
                (p.1 * s).round() as usize % R,
            )
        };
        assert!(
            blind.iter().any(|b| sample(b.start_points[0]) < sea),
            "the geometric centroid is supposed to land in the sea here"
        );

        let ground = StartGround::new(
            &height,
            &ctx,
            BuildabilityOptions {
                sea_level: sea,
                ..Default::default()
            },
        );
        let seeing = startboxes_on(&d, "mirrorX", Some(&ground));
        for b in &seeing {
            assert!(
                b.grounded,
                "{} was not placed on checked ground",
                b.name_short
            );
            let p = b.start_points[0];
            assert!(
                sample(p) >= sea,
                "{} starts under water at {p:?}",
                b.name_short
            );
        }
        // Both teams get the same ground: one is the mirror of the other.
        let w = f64::from(d.elmos_x);
        assert!((seeing[0].start_points[0].0 - (w - seeing[1].start_points[0].0)).abs() < 1e-9);
        assert!((seeing[0].start_points[0].1 - seeing[1].start_points[0].1).abs() < 1e-9);
    }

    #[test]
    fn startboxes_mirror_exactly() {
        let d = crate::spring::derive(12, 12);
        let boxes = default_startboxes(&d, "mirrorX");
        let lua = startboxes_lua(&boxes);
        assert!(lua.contains("nameShort = \"W\""));
        assert!(lua.contains("nameShort = \"E\""));
        let a = &boxes[0].boxes[0];
        let b = &boxes[1].boxes[0];
        let w = f64::from(d.elmos_x);
        // Every corner of the east box is the mirror of a west corner.
        for (x, _) in a {
            assert!(b.iter().any(|(bx, _)| (bx - (w - x)).abs() < 1e-9));
        }
    }

    /// An edited box has to reach the bake, and the start point inside it has
    /// to still be chosen from the terrain — a box says where a team starts,
    /// not where its commander stands.
    #[test]
    fn an_edited_box_is_used_and_still_gets_its_point_from_the_ground() {
        let d = crate::spring::derive(12, 12);
        let (w, h) = (6144.0, 6144.0);
        // `quad`'s north-east box has room to move in both directions; the
        // `mirrorX` west box is already against two edges and would only
        // exercise the clamp.
        let mut areas = default_areas(&d, "quad");
        assert_eq!(areas.len(), 4);
        let before = areas[1].centre();
        areas[1].translate(-500.0, 700.0, w, h);
        let after = areas[1].centre();
        assert!((after.0 - (before.0 - 500.0)).abs() < 1e-6);
        assert!((after.1 - (before.1 + 700.0)).abs() < 1e-6);

        // Shoved hard into a corner it stops, keeping its size rather than
        // being squashed against the edge.
        let (bx0, bz0, bx1, bz1) = areas[1].bounds();
        areas[1].translate(-90000.0, -90000.0, w, h);
        let (x0, z0, x1, z1) = areas[1].bounds();
        assert!(
            x0.abs() < 1e-9 && z0.abs() < 1e-9,
            "did not stop at the edge"
        );
        assert!(
            ((x1 - x0) - (bx1 - bx0)).abs() < 1e-6 && ((z1 - z0) - (bz1 - bz0)).abs() < 1e-6,
            "the box changed size when it hit the edge"
        );

        let boxes = startboxes_from(&areas, &d, "quad", None);
        assert_eq!(boxes.len(), 4);
        // The emitted polygon is the edited one, not the derived one.
        let mut got = boxes[1].boxes[0].clone();
        got.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let mut want = areas[1].poly.clone();
        want.sort_by(|a, b| a.partial_cmp(b).unwrap());
        assert_eq!(got, want);
        // And the start point is inside it.
        let (sx, sz) = boxes[1].start_points[0];
        assert!(
            sx >= x0 - 1.0 && sx <= x1 + 1.0 && sz >= z0 - 1.0 && sz <= z1 + 1.0,
            "start point {sx},{sz} is outside its own box"
        );
    }

    /// Scaling keeps a box centred where it was, so making bases bigger does
    /// not quietly slide them toward the map centre.
    #[test]
    fn scaling_a_box_keeps_its_centre() {
        let d = crate::spring::derive(12, 12);
        let mut a = default_areas(&d, "quad")[1].clone();
        let before = a.centre();
        let (x0, z0, x1, z1) = a.bounds();
        a.scale(0.5, 6144.0, 6144.0);
        let after = a.centre();
        assert!((before.0 - after.0).abs() < 1e-6 && (before.1 - after.1).abs() < 1e-6);
        let (nx0, nz0, nx1, nz1) = a.bounds();
        assert!(((nx1 - nx0) - (x1 - x0) * 0.5).abs() < 1e-6);
        assert!(((nz1 - nz0) - (z1 - z0) * 0.5).abs() < 1e-6);
    }

    /// Setting bounds gives a rectangle, in order, on the map, with area.
    #[test]
    fn bounds_editing_produces_a_usable_rectangle() {
        let d = crate::spring::derive(12, 12);
        let (w, h) = (6144.0, 6144.0);
        let mut a = default_areas(&d, "mirrorX")[0].clone();
        // Given backwards and out of range on purpose.
        a.set_bounds(5000.0, -400.0, 1000.0, 9000.0, w, h);
        let (x0, z0, x1, z1) = a.bounds();
        assert_eq!((x0, x1), (1000.0, 5000.0), "corners were not sorted");
        assert_eq!(
            (z0, z1),
            (0.0, 6144.0),
            "corners were not clamped to the map"
        );
        assert_eq!(a.shape(), Shape::Rect);
        assert_eq!(a.poly.len(), 4);

        // A degenerate box would have nowhere to put a start point.
        a.set_bounds(2000.0, 2000.0, 2000.0, 2000.0, w, h);
        let (x0, z0, x1, z1) = a.bounds();
        assert!(
            x1 - x0 >= 64.0 && z1 - z0 >= 64.0,
            "a zero-area box was allowed"
        );
    }

    /// A wedge keeps the ground the rectangle covered and stays inside it, so
    /// switching shape does not move a base across the map.
    #[test]
    fn a_wedge_stays_inside_the_bounds_it_came_from() {
        let d = crate::spring::derive(12, 12);
        let (w, h) = (6144.0, 6144.0);
        for i in 0..4 {
            let mut a = default_areas(&d, "quad")[i].clone();
            let before = a.bounds();
            a.set_shape(Shape::Wedge, w, h);
            assert_eq!(a.shape(), Shape::Wedge);
            assert_eq!(a.poly.len(), 3);
            for (x, z) in &a.poly {
                assert!(
                    *x >= before.0 - 1e-9 && *x <= before.2 + 1e-9,
                    "wedge corner {x} outside {before:?}"
                );
                assert!(*z >= before.1 - 1e-9 && *z <= before.3 + 1e-9);
            }
            // And back again is the rectangle it started as.
            a.set_shape(Shape::Rect, w, h);
            assert_eq!(a.bounds(), before);
        }
    }

    /// A wedge still holds a start point, which is the only thing a box is
    /// actually for.
    #[test]
    fn a_wedge_still_gets_a_start_point_inside_it() {
        let d = crate::spring::derive(12, 12);
        let mut areas = default_areas(&d, "quad");
        for a in areas.iter_mut() {
            a.set_shape(Shape::Wedge, 6144.0, 6144.0);
        }
        let boxes = startboxes_from(&areas, &d, "quad", None);
        assert_eq!(boxes.len(), 4);
        for (b, a) in boxes.iter().zip(areas.iter()) {
            let (sx, sz) = b.start_points[0];
            let (x0, z0, x1, z1) = a.bounds();
            assert!(
                sx >= x0 - 1.0 && sx <= x1 + 1.0 && sz >= z0 - 1.0 && sz <= z1 + 1.0,
                "start point {sx},{sz} is outside its wedge {:?}",
                a.bounds()
            );
        }
    }
}
