-- mapconfig/map_metal_layout.lua
-- Generated by MapForge. 14 spots, coordinates in elmos,
-- snapped to the 16-elmo metal grid (Game.metalMapSquareSize).
-- Explicit metal values are written so Zero-K does not integrate the
-- metalmap raster (mex_spot_finder.lua: DEFAULT_MEX_INCOME = 2, values <= 0.2 are dropped).
-- Symmetry: rot180

return {
	spots = {
		{ x = 384, z = 288, metal = 2 },
		{ x = 5760, z = 5856, metal = 2 },
		{ x = 1104, z = 288, metal = 2 },
		{ x = 5040, z = 5856, metal = 2 },
		{ x = 1824, z = 288, metal = 2 },
		{ x = 4320, z = 5856, metal = 2 },
		{ x = 2544, z = 288, metal = 2 },
		{ x = 3600, z = 5856, metal = 2 },
		{ x = 3312, z = 288, metal = 2 },
		{ x = 2832, z = 5856, metal = 2 },
		{ x = 5280, z = 288, metal = 2 },
		{ x = 864, z = 5856, metal = 2 },
		{ x = 4560, z = 720, metal = 2 },
		{ x = 1584, z = 5424, metal = 2 },
	},
}