-- Generated by MapForge. Size 12x12 (6144x6144 elmos, mapx=768)
local mapinfo = {
  name        = "Golden",
  shortname   = "Golden",
  description = "",
  author      = "",
  version     = "1.0",
  mapfile     = "maps/golden.smf",
  modtype     = 3,
  maphardness = 100,
  gravity     = 120,
  tidalStrength = 18,
  maxMetal    = 1.7,
  extractorRadius = 100,
  voidWater   = false,
  autoShowMetal = true,
  smf = {
    minHeight = -80,
    maxHeight = 420,
  },
  terrainTypes = {
    [0] = { name = 'Default', hardness = 1.0, receiveTracks = true,
            moveSpeeds = { tank = 1.0, kbot = 1.0, hover = 1.0, ship = 1.0 } },
    [1] = { name = 'Rock',    hardness = 4.0, receiveTracks = false,
            moveSpeeds = { tank = 0.8, kbot = 0.9, hover = 1.0, ship = 1.0 } },
  },
}
return mapinfo